
# joint_tf -- LR x WD grid (LR: 0.001 0.0005 0.0001 0.00005 | WD: 0.01 0.001 0.0001 0.0)
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.0

CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 1 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.0

CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.001   --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0005  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.0001  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 2 --validate_with accuracy --batch_size 32 --no_model_save --lr 0.00005 --wd 0.0

CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.001   --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.001   --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.001   --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.001   --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0005  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0005  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0005  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0005  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0001  --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0001  --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0001  --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.0001  --wd 0.0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.00005 --wd 0.01
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.00005 --wd 0.001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.00005 --wd 0.0001
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src python -m synib.entrypoints.show --config run/configs/FactorCL/Mustard/release/VT/joint_tf.json --default_config run/configs/FactorCL/Mustard/default_config_mustard_VT.json --fold 0 --validate_with accuracy --batch_size 32 --lr 0.00005 --wd 0.0
