
# cache_synibu_lora -- LR x WD grid, fixed: --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1
# (LR: 0.001 0.0005 0.0001 0.00005 | WD: 0.01 0.001 0.0001 0.0)
# NOTE: see also l x lsparse grid at the bottom of this file
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.0
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.0
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.0
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.0


# cache_synibu_lora -- l x lsparse grid, fixed: --lr 0.0005 --wd 0.0001
# (l: 0.01 0.1 1 10 | lsparse: 0.1 1 10)
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.01  --perturb_lsparse 0.1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.01  --perturb_lsparse 1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.01  --perturb_lsparse 10
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.1   --perturb_lsparse 0.1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.1   --perturb_lsparse 1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.1   --perturb_lsparse 10
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 1     --perturb_lsparse 0.1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 1     --perturb_lsparse 1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 1     --perturb_lsparse 10
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 10    --perturb_lsparse 0.1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 10    --perturb_lsparse 1
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synibu_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 10    --perturb_lsparse 10
