
# cache_video_lora -- LR x WD grid (LR: 0.001 0.0005 0.0001 0.00005 | WD: 0.01 0.001 0.0001 0.0)
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.001   --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.001   --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.001   --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.001   --wd 0.0
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0005  --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0005  --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0005  --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0005  --wd 0.0
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001  --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001  --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001  --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001  --wd 0.0
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005 --wd 0.01
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005 --wd 0.001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005 --wd 0.0001
CUDA_VISIBLE_DEVICES=3 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_video_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005 --wd 0.0
