
# cache_full_ft -- LR x WD grid (LR: 0.0001 0.00005 0.00001 0.000005 | WD: 0.01 0.001 0.0001 0.0)
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001    --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001    --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001    --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.0001    --wd 0.0
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005   --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005   --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005   --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00005   --wd 0.0
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00001   --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00001   --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00001   --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.00001   --wd 0.0
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.000005  --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.000005  --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.000005  --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --no_model_save --lr 0.000005  --wd 0.0


# cache_full_ft --finetune_layers "20,21,22,23,24,25,26,27" -- LR x WD grid (same range)
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.0001    --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.0001    --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.0001    --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.0001    --wd 0.0
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00005   --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00005   --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00005   --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00005   --wd 0.0
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00001   --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00001   --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00001   --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.00001   --wd 0.0
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.000005  --wd 0.01
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.000005  --wd 0.001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.000005  --wd 0.0001
CUDA_VISIBLE_DEVICES=7 PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_full_ft.json --default_config run/configs/MUStARD/default_config_mustard_cache_mib.json --fold 0 --validate_with accuracy --batch_size 8 --finetune_layers "20,21,22,23,24,25,26,27" --no_model_save --lr 0.000005  --wd 0.0
