
# cache_synib_lora -- LR x WD grid, fixed: --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1
# (LR: 0.001 0.0005 0.0001 0.00005 | WD: 0.01 0.001 0.0001 0.0)
# NOTE: see also l x lsparse grid at the bottom of this file
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 4 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.01

# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.01
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.0001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.001   --wd 0.0
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.01
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.0001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0005  --wd 0.0
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.01
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.0001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.0001  --wd 0.0
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.01
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.0001
# PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --l 1 --perturb learned --perturb_fill ema --perturb_lsparse 0.1 --no_model_save --lr 0.00005 --wd 0.0

 
# cache_synib_lora -- l x lsparse grid, fixed: --lr 0.0005 --wd 0.0001
# (l: 0.01 0.1 1 10 | lsparse: 0.1 1 10)
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.01  --perturb_lsparse 0.1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.01  --perturb_lsparse 1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.01  --perturb_lsparse 10
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.1   --perturb_lsparse 0.1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.1   --perturb_lsparse 1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 0.1   --perturb_lsparse 10
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 1     --perturb_lsparse 0.1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 1     --perturb_lsparse 1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 1     --perturb_lsparse 10
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 10    --perturb_lsparse 0.1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 10    --perturb_lsparse 1
PYTHONPATH=src python -m synib.entrypoints.train --config run/configs/MUStARD/cache_synib_lora.json --default_config run/configs/MUStARD/default_config_mustard_cache_orcd.json --fold 0 --validate_with accuracy --batch_size 6 --perturb learned --perturb_fill ema --no_model_save --lr 0.0005 --wd 0.0001 --l 10    --perturb_lsparse 10


 
